name: resusable-workflow-caller

on:
  push:
    branches: none # [ main ]
  pull_request:
    branches: none # [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: Wepstern/reusable-called/.github/workflows/reusable-workflow-called.yaml@main
    with:
      workflows-ref: main
    secrets:
      GH_ACCESSTOKEN: ${{ secrets.GH_ACCESSTOKEN }}
