name: resusable-workflow-caller

on:
  push:
    branches: none # [ main ]
  pull_request:
    branches: none # [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: reusable-caller
  cancel-in-progress: false

jobs:
  call-reusable-workflow-1:
    uses: Wepstern/reusable-called/.github/workflows/reusable-workflow-called.yaml@main
    with:
      workflows-ref: main
    # secrets:
    #   GH_ACCESSTOKEN: ${{ secrets.GH_ACCESSTOKEN }}

  call-reusable-workflow-2:
    uses: Wepstern/reusable-called/.github/workflows/reusable-workflow-called.yaml@main
    with:
      workflows-ref: main
    # secrets:
    #   GH_ACCESSTOKEN: ${{ secrets.GH_ACCESSTOKEN }}

  call-reusable-workflow-3:
    uses: Wepstern/reusable-called/.github/workflows/reusable-workflow-called.yaml@main
    with:
      workflows-ref: main
    # secrets:
    #   GH_ACCESSTOKEN: ${{ secrets.GH_ACCESSTOKEN }}
    
  call-reusable-workflow-4:
    uses: Wepstern/reusable-called/.github/workflows/reusable-workflow-called.yaml@main
    with:
      workflows-ref: main
    # secrets:
    #   GH_ACCESSTOKEN: ${{ secrets.GH_ACCESSTOKEN }}

  call-reusable-workflow-5:
    uses: Wepstern/reusable-called/.github/workflows/reusable-workflow-called.yaml@main
    with:
      workflows-ref: main
    # secrets:
    #   GH_ACCESSTOKEN: ${{ secrets.GH_ACCESSTOKEN }}
